name: elevate_task
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  http: ^1.2.2
  injectable: ^2.4.4
  get_it: ^7.7.0
  dartz: ^0.10.1
  cached_network_image: ^3.4.1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  injectable_generator: ^2.6.2
  build_runner: ^2.4.12

flutter:
  uses-material-design: true

  assets:
    - assets/
